# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-31 12:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatTogether', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 3, 31, 20, 53, 43, 540049)),
        ),
    ]
