# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-31 12:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatTogether', '0003_auto_20180331_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 3, 31, 20, 59, 33, 676846)),
        ),
    ]
