# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-01 02:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatTogether', '0004_auto_20180331_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 4, 1, 10, 40, 40, 408912)),
        ),
    ]
