# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-01 04:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatTogether', '0006_auto_20180401_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 4, 1, 12, 8, 38, 208783)),
        ),
    ]
